enum {
    STATE_START,
    STATE_LOAD_LIST,
    STATE_LOADING_LIST,
    STATE_LOADED_LIST,
    STATE_DISPLAY_LIST,
    STATE_LOAD_TRACK,
    STATE_LOADING_TRACK,
    STATE_LOADED_TRACK,
    STATE_FAILED_TRACK,
    STATE_START_TRACK,
    STATE_EXIT_TO
}
